using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelloWorld
{
    public class Flipcoin
    {
        public static void Flipcoinpercentage() {
            Console.WriteLine("Please enter the value for number of flips");
            int head = 0;
            int tail = 0;

            double headpercentage = 0.0;
            double tailpercentage = 0.0;

            int flip=Convert.ToInt32(Console.ReadLine());

            if (flip > 0)
            {
                for (int i = 0; i < flip; i++) {
                    Random random = new Random();

                    int num = random.Next(2);

                    Console.WriteLine("Random numbers generated by system " + num);

                    if (num == 0)
                    {
                        Console.WriteLine("It is tail");
                        tail = tail++;
                    }
                    else
                    {
                        Console.WriteLine("It is Head");
                        head = head++;
                    }

                    Console.WriteLine("The head Count is " + head);
                    Console.WriteLine("The tail Count is " + tail);

                    headpercentage = head * 100 / flip;
                    tailpercentage = tail * 100 / flip;
                    Console.WriteLine("Head percentage " + headpercentage);
                    Console.WriteLine("tail percentage " + tailpercentage);

                
                }
            
            }


            

           

        }
    }
}
